name: Code checks
on: [pull_request]

jobs:
  code-check:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.19.0'
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
